apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
spec:
  minReplicas: {{MIN_REPLICAS}}
  maxReplicas: {{MAX_REPLICAS}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{DEPLOYMENT_NAME}}
  metrics:
    - type: Resource  # 确保这里设置为支持的类型
      resource:
        name: cpu
        target:
          type: Utilization  # 目标类型
          averageUtilization: {{TARGET_UTILIZATION}}  # CPU 利用率目标
