apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{INGRESS_NAME}}
  namespace: {{NAMESPACE}}
  annotations:
    nginx.ingress.kubernetes.io/service-weight: ''  # 根据需要添加其他注解
spec:
  ingressClassName: nginx
  rules:
    - host: {{HOST}}  # 这里是你的域名
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{SERVICE_NAME}}  # 需要与 Service 名称匹配
                port:
                  number: {{SERVICE_PORT}}  # 需要与 Service 端口匹配