apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_LABEL}}  # 这里需要与你的 Deployment 中的标签匹配
  ports:
    - port: {{SERVICE_PORT}}  # 服务端口
      targetPort: {{TARGET_PORT}}  # 目标端口
      protocol: TCP